import type { Venue } from "@/lib/venues";

const weekdayLunch = {
  mon: [{ open: "10:30", close: "18:00" }],
  tue: [{ open: "10:30", close: "18:00" }],
  wed: [{ open: "10:30", close: "18:00" }],
  thu: [{ open: "10:30", close: "18:00" }],
  fri: [{ open: "10:30", close: "16:00" }],
};

export const MOCK_VENUES: Venue[] = [
  {
    id: "venue-cherry-cart",
    slug: "cherry-cart",
    type: "truck",
    name: "Cherry Cart",
    description:
      "A quick campus stop for griddled sandwiches, loaded fries, and weekday lunch.",
    status: "published",
    mapZone: "tyler-trucks",
    location: "Norris Street between 12th and 13th",
    building: "Engineering Building",
    lat: 39.98305,
    lng: -75.15415,
    acceptsCash: true,
    acceptsCard: true,
    cuisines: ["american"],
    hours: weekdayLunch,
    lastVerifiedAt: "2026-07-12",
  },
  {
    id: "venue-compass-kitchen",
    slug: "compass-kitchen",
    type: "truck",
    name: "Compass Kitchen",
    description:
      "Rice platters, falafel, and warm pita made for a fast lunch between classes.",
    status: "published",
    mapZone: "w-montgomery",
    location: "Montgomery Avenue near 13th Street",
    building: "Student Center",
    lat: 39.98015,
    lng: -75.15505,
    acceptsCash: true,
    acceptsCard: true,
    cuisines: ["halal"],
    hours: {
      ...weekdayLunch,
      mon: [{ open: "11:00", close: "19:00" }],
      tue: [{ open: "11:00", close: "19:00" }],
      wed: [{ open: "11:00", close: "19:00" }],
      thu: [{ open: "11:00", close: "19:00" }],
    },
    lastVerifiedAt: "2026-07-08",
  },
  {
    id: "venue-twelfth-tacos",
    slug: "twelfth-street-tacos",
    type: "truck",
    name: "Twelfth Street Tacos",
    description: "Tacos, burritos, and bowls with a short, dependable menu.",
    status: "published",
    mapZone: "serc-trucks",
    location: "12th Street south of Norris",
    building: "Engineering Building",
    // On the 12th St centerline, inside the serc-trucks map zone —
    // venues.test.ts exercises spatial zone filtering with this venue.
    lat: 39.98155,
    lng: -75.15341,
    acceptsCash: true,
    acceptsCard: false,
    cuisines: ["mexican"],
    hours: weekdayLunch,
    lastVerifiedAt: "2026-06-29",
  },
  {
    id: "venue-island-bowl",
    slug: "island-bowl",
    type: "truck",
    name: "Island Bowl",
    description: null,
    status: "published",
    mapZone: "tyler-trucks",
    location: "Norris Street near 12th Street",
    building: "Engineering Building",
    lat: 39.98312,
    lng: -75.15295,
    acceptsCash: null,
    acceptsCard: true,
    cuisines: ["caribbean"],
    hours: null,
    lastVerifiedAt: null,
  },
  {
    id: "venue-campus-wok",
    slug: "campus-wok",
    type: "truck",
    name: "Campus Wok",
    description: "Made-to-order noodles and rice dishes.",
    status: "published",
    mapZone: "student-center",
    location: "Montgomery Avenue near 12th Street",
    building: "Student Center",
    lat: 39.98008,
    lng: -75.15345,
    acceptsCash: true,
    acceptsCard: true,
    cuisines: ["chinese"],
    hours: weekdayLunch,
    lastVerifiedAt: "2026-07-03",
  },
  {
    id: "venue-fruit-line",
    slug: "fruit-line",
    type: "truck",
    name: "Fruit Line",
    description: "Fresh fruit cups, smoothies, and cold drinks.",
    status: "published",
    mapZone: "other",
    location: "11th Street near Polett Walk",
    building: "Charles Library",
    lat: 39.98175,
    lng: -75.15095,
    acceptsCash: true,
    acceptsCard: null,
    cuisines: ["fruit"],
    hours: null,
    lastVerifiedAt: "2026-05-21",
  },
  {
    id: "venue-old-lunch-counter",
    slug: "old-lunch-counter",
    type: "restaurant",
    name: "Old Lunch Counter",
    description: "This venue is no longer operating.",
    status: "retired",
    mapZone: "other",
    location: "Near Temple Main Campus",
    lat: 39.98195,
    lng: -75.1521,
    acceptsCash: null,
    acceptsCard: null,
    cuisines: ["american"],
    hours: null,
    lastVerifiedAt: "2026-03-14",
  },
];

export function getMockVenueBySlug(slug: string): Venue | undefined {
  return MOCK_VENUES.find((venue) => venue.slug === slug);
}
